FROM node as build
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
WORKDIR /app/client
RUN npm install
RUN npm run build
WORKDIR /app
CMD ["npm", "start"]


# FROM nginx
# COPY --from=build /app/build /usr/share/nginx/html